### ISSUE TITLE
Compat with Expanded Storage double chests

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/crafting-station#54]
`Minecraft v1.15.2`
`Forge v31.1.61`
`Crafting Station v3.1.0`
[`Expanded Storage v1.1.8`](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge) 

Currently, if I make a double iron chest using the Chest Mutator item, the Crafting Station doesn't recognize this, so the inventory shown is only that of a single iron chest without a scrollbar.
Is this possible to add support for?

**Comment by choekstr** [comment]
I came here to report this as well.  It seems like the expanded storage chests are unique in how they treat inventories.  an iron chest is larger than vanilla but you can stack 2 iron chests and it is larger than double vanilla chests.  You can also stack them vertically which is cool but odd. :) 
![image](https://user-images.githubusercontent.com/161085/100527500-a3ede900-3198-11eb-8d7a-7aa996efac0a.png)

Double expanded storage iron chests:
![image](https://user-images.githubusercontent.com/161085/100527514-bff18a80-3198-11eb-9110-b4aba1801966.png)

View from crafting station with the last items showing (no scrollbar and not showing the last 6 items) and you can see from the previous screenshot that it only shows part of the inventory:
![image](https://user-images.githubusercontent.com/161085/100527555-29719900-3199-11eb-8691-50052c575083.png)

**Comment by Tfarcenim** [comment]
Not looking forward to compat with this, likely lots of hardcoding

**Comment by choekstr** [comment]
There's nothing like sizeof(getinventory(adjacent_chest)) routine that you can leverage to just query the slots and then build your scrolling window accordingly?  

Could you just make the inventory shown a lot bigger?  I remember you said you couldn't change the size of the side inventory shown when in the crafting station but that was back when you were still using the tinker's code.  Since you rewrote it I assume there is a reason you had to keep that same/similar size instead of making it much larger to fill the screen and gui sizing?

Not sure if this mod will take off or not, but it's used in TNP Limitless 3 modpack, which isn't a hugely popular pack.  I guess it depends if more of the popular "larger chest" mods are ported to 1.16 quickly.

**Comment by choekstr** [comment]
It seems like a single upgraded chest causes no issue, so a diamond level chest works, just a double iron or higher chest causes issues.

**Comment by Tfarcenim** [comment]
If I can find a way to check for double chests without hardcoding, I will fix this, otherwise no.

**Comment by Tfarcenim** [comment]
This is on their end, they need to make sure to return the correct inventory on the clientside
