### ISSUE TITLE
Dupe_bug

### ISSUE THREAD

**Issue by sysyss** [Tfarcenim/crafting-station#79]
0. choose item and get more than 1 stack. for example. kind like ingot need more than 65.(1 stack and 1 )
1. all choose item place on table
2. Place chest on side of table(Double chest is option or not is i don't know). chest need enough empty space
2. fill your inventory full. anything  is okay. choose item are can not get anymore in your inventory.
3. open table and , shift + drag on item. 

if dupe is working, than only some item that less than one stack is move in and other chest and when drag(with keep shift) repeat on item. dupe stack of item

result ex.
on table 64 and 1 of iron ingot
drag start.
1 iron move into chest table has stack.
keep drag.
one stack iron is dupe and move into chest. still stack of iron is hold on table

**Comment by Paladin62** [comment]
I was able to consistently recreate this defect on Forge 36.1.0 and craftingstation-4.1.1.jar

1. Set Crafting Station with single chest adjacent.
2. Place 1 full stack of any stackable item into chest. ie. 64 diamonds
3. Place additional partial stack of same item into chest. ie. 1 diamond
4. Fill personal inventory so that no items from chest will either stack or find empty slot. ie. Put single flower in each of your personal inventory slots.
5. Open Crafting Station
6. Move stack of 64 items into Crafting Station slot
7. Hold shift and right click stack in Crafting station
8. Stack of 64 will remain in Crafting Station while stack of 64 will also be placed into chest.
9. This can be repeated until all chest slots are full.

**Comment by Tfarcenim** [comment]
Was this verified on an instance with 0 other mods?  There's been quite a few broken inventory management mods causing dupe dugs lately,

**Comment by Paladin62** [comment]
Yes.  I have verified with no other mods.

**Comment by Tfarcenim** [comment]
This was not fun to track down, but fixed hopefully
